### ISSUE TITLE
problem with "no panic" behaviour (since v1.8.0)

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#190]
Consider this code ran on [this demo](http://replay190.valve.net/730/003403000919749558509_1688416666.dem.bz2):
```go
func main() {
	pathToDemoFile := "D:\\Games\\steamApps\\common\\Counter-Strike Global Offensive\\csgo\\replays\\match730_003403000919749558509_1688416666_190.dem"
	f, err := os.Open(pathToDemoFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	p := dem.NewParser(f)

	p.RegisterEventHandler(func(e events.GrenadeProjectileThrow) {
		fmt.Println(p.GameState().IngameTick())
		fmt.Printf("a grenade was thrown from %v by %s\n", e.Projectile.Thrower.Position, e.Projectile.Thrower)
	})

	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```

On tick number `137964` there is a `GrenadeProjectileThrow` event with `e.Projectile.Thrower` being `nil`. With `v1.7.6` we get this output: 
[176 parse to end.txt](https://github.com/markus-wa/demoinfocs-golang/files/4361073/176.parse.to.end.txt)

Showing only last lines:
```
137824
a grenade was thrown from (1079.793334960937500000000000, -192.934982299804687500000000, -166.622924804687500000000000) by noodesi csgo.run
137920
a grenade was thrown from (-449.903350830078125000000000, -2129.980957031250000000000000, -179.968750000000000000000000) by boss32401CASEDROP.EU
137964
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x8142f5]

goroutine 19 [running]:
github.com/markus-wa/demoinfocs-golang.recoverFromUnexpectedEOF(...)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/parsing.go:120
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities.func1(0xc0000fa000)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/entities.go:14 +0x139
panic(0x870e00, 0xd345c0)
	C:/Program Files/Go/src/runtime/panic.go:522 +0x1c3
main.main.func1(0xc00139f1a0)
	C:/Users/admin/go/src/demoinfocs-test-cases/main.go:23 +0xc5
reflect.Value.call(0x84e480, 0xc000054530, 0x13, 0x8ea487, 0x4, 0xc000d87a18, 0x1, 0x1, 0x1, 0xd38b20, ...)
	C:/Program Files/Go/src/reflect/value.go:447 +0x468
reflect.Value.Call(0x84e480, 0xc000054530, 0x13, 0xc000d87a18, 0x1, 0x1, 0x38, 0x50, 0xc0026a05a0)
	C:/Program Files/Go/src/reflect/value.go:308 +0xab
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000fa090, 0x87e7a0, 0xc00139f1a0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:48 +0x25a
github.com/markus-wa/demoinfocs-golang.(*Parser).bindGrenadeProjectiles.func1()
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/datatables.go:400 +0xf1
github.com/markus-wa/demoinfocs-golang/sendtables.(*ServerClass).newEntity(0xc0004063c0, 0xc0000f02a0, 0x1d0, 0xd4a04dec)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/sendtables.go:125 +0x339
github.com/markus-wa/demoinfocs-golang/sendtables.(*SendTableParser).ReadEnterPVS(0xc0000f0150, 0xc0000f02a0, 0x1d0, 0xd59be0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/st_parser.go:290 +0xcd
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities(0xc0000fa000, 0xc002be59e0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/entities.go:43 +0x26b
reflect.Value.call(0x84dfc0, 0xc0000544a0, 0x13, 0x8ea487, 0x4, 0xc000d87f68, 0x1, 0x1, 0x2, 0xd38b20, ...)
	C:/Program Files/Go/src/reflect/value.go:447 +0x468
reflect.Value.Call(0x84dfc0, 0xc0000544a0, 0x13, 0xc000d87f68, 0x1, 0x1, 0x0, 0x0, 0x0)
	C:/Program Files/Go/src/reflect/value.go:308 +0xab
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000fa020, 0x8d3f40, 0xc002be59e0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:48 +0x25a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000fa020, 0xc000146000)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:97 +0xfc
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:83 +0x158

Process finished with exit code 2
```

As expected, we get `panic` message followed by a stack trace. But with `v1.8.0` we get this: 
[180 parse to end.txt](https://github.com/markus-wa/demoinfocs-golang/files/4361089/180.parse.to.end.txt)
Last few lines:
```
137920
a grenade was thrown from (-449.903350830078125000000000, -2129.980957031250000000000000, -179.968750000000000000000000) by boss32401CASEDROP.EU
137964
138214
a grenade was thrown from (-649.914367675781250000000000, -1686.561401367187500000000000, -174.224746704101562500000000) by sluz
138338
a grenade was thrown from (399.946289062500000000000000, -15.299140930175781250000000, -200.308837890625000000000000) by z3ph
138490
a grenade was thrown from (399.946289062500000000000000, -15.299140930175781250000000, -200.308837890625000000000000) by z3ph
139523
a grenade was thrown from (-735.221374511718750000000000, -1150.097167968750000000000000, -167.968750000000000000000000) by boss32401CASEDROP.EU
139557
a grenade was thrown from (-995.121459960937500000000000, -1399.550903320312500000000000, -167.968750000000000000000000) by M4KS

Process finished with exit code 0
```
So... nothing at all, just a missed line. This can be worked around by replacing
```go
	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
```
with
```go
	next, err := p.ParseNextFrame()
	if err != nil {
		panic(err)
	}
	for next {
		next, err = p.ParseNextFrame()
		if err != nil {
			panic(err)
		}
	}
```
so we get this output: 
[180 parse next frame.txt](https://github.com/markus-wa/demoinfocs-golang/files/4361103/180.parse.next.frame.txt)
but this time the error message is not very informative and doesn't allow us to track down the issue:
```
137964
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
main.main()
	C:/Users/admin/go/src/demoinfocs-test-cases/main.go:33 +0x1da
```
(the 33rd line is of course `panic(err)`)

With 'v1.7.6' we get this: 
[176 parse next frame.txt](https://github.com/markus-wa/demoinfocs-golang/files/4361107/176.parse.next.frame.txt)
and it is pretty much the same as in the first case.

This is really a problem because to be able to find the origin of the problem in my application I had to rollback to `v1.7.6`. I realize that it is really an error on my side (not to check `e.Projectile.Thrower` for being `nil`) but still in previous version it was much easier to debug and I honestly don't believe that you can write code entirely free from such mistakes as mine 😄

**Comment by markus-wa** [comment]
Ahhhh yikes! I totally didn't think of this case.
Yeah you are absolutely right and this wasn't intended.

Ideally we should panic if the error came from user code (e.g. `RegiserXXXHandler`).
