### ISSUE TITLE
CSGO Demo crashes with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sarim-hk** [markus-wa/demoinfocs-golang#415]
**Describe the bug**
Ran my code on the demo linked below, got this error (full stacktrace): https://pastebin.com/Zg3b09Pb
.txt output before error: https://pastebin.com/uxa0UqE7

**To Reproduce**
~~https://drive.google.com/file/d/1v93j54jcK8MeFpQhMbju7KrOTI6yb_XI/view?usp=sharing Demo link~~
updated correct demo link here https://drive.google.com/file/d/1qBvWiLD-ToybuUoNN7pP-YjIGWC6PZIn/view?usp=sharing

Code:
```go
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/golang/geo/r3"
	dem "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs"
	events "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/events"
)

type KillEvent struct {
	EventType      string
	KillerPosition r3.Vector
	VictimPosition r3.Vector
	Weapon         string
}

type BombEvent struct {
	/*
		Bombsite 65 = A
		Bombsite 66 = B
	*/
	EventType string
	Bombsite  int
}

type GrenadeProjectileEvent struct {
	EventType string
	Positions []r3.Vector
	Grenade   string
}

type RoundEndEvent struct {
	/*
		Team 2 = Terrorists
		Team 3 = Counter-Terrorists
	*/
	EventType string
	Winner    int
}

func CommandLineArgs() *string {
	path := flag.String("path", "N/A", "The path to the demo.")
	flag.Parse()
	return path
}

func OpenDemo(path *string) *os.File {
	f, err := os.Open(*path)
	if err != nil {
		log.Panic("failed to open demo file: ", err)
	}
	return f
}

func MakeParser(f *os.File) dem.Parser {
	p := dem.NewParser(f)
	return p
}

func HandleHeader(p dem.Parser) {
	header, _ := p.ParseHeader()
	header_marshalled, _ := json.Marshal(header)
	fmt.Println(string(header_marshalled))
}

func main() {
	path := CommandLineArgs()
	demo_file := OpenDemo(path)
	p := MakeParser(demo_file)

	HandleHeader(p)

	p.RegisterEventHandler(func(e events.Kill) {
		event := KillEvent{
			EventType:      "Kill",
			KillerPosition: e.Killer.LastAlivePosition,
			VictimPosition: e.Victim.LastAlivePosition,
			Weapon:         e.Weapon.String(),
		}
		event_marshalled, _ := json.Marshal(event)
		fmt.Println(string(event_marshalled))
	})

	p.RegisterEventHandler(func(e events.BombPlanted) {
		event := BombEvent{
			EventType: "BombPlanted",
			Bombsite:  int(e.BombEvent.Site),
		}
		event_marshalled, _ := json.Marshal(event)
		fmt.Println(string(event_marshalled))
	})

	p.RegisterEventHandler(func(e events.BombDefused) {
		event := BombEvent{
			EventType: "BombDefused",
			Bombsite:  int(e.BombEvent.Site),
		}
		event_marshalled, _ := json.Marshal(event)
		fmt.Println(string(event_marshalled))
	})

	p.RegisterEventHandler(func(e events.GrenadeProjectileDestroy) {
		event := GrenadeProjectileEvent{
			EventType: "GrenadeProjectileDestroy",
			Positions: e.Projectile.Trajectory,
			Grenade:   e.Projectile.WeaponInstance.String(),
		}
		event_marshalled, _ := json.Marshal(event)
		fmt.Println(string(event_marshalled))
	})

	p.RegisterEventHandler(func(e events.RoundEnd) {
		event := RoundEndEvent{
			EventType: "RoundEnd",
			Winner:    int(e.Winner),
		}
		event_marshalled, _ := json.Marshal(event)
		fmt.Println(string(event_marshalled))
	})

	// Parse to end
	err := p.ParseToEnd()
	if err != nil {
		log.Panic("failed to parse demo: ", err)
	}
}

```

**Library version**
v3.3.0

**Additional context**
Running Windows 11, and a noob with Go

**Comment by dabbers** [comment]
Seeing the same thing with a similarly simple repro:

```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"

	dem "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
	"github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
)

func main() {
	c := make(chan struct{}, 0)

	fmt.Println("CS2Demo Initialized")
	content, err := os.Open("./003636976135146832149_1877073722.dem")
	if err != nil {
		fmt.Println("Err")
	}
	parseInternal(content)
	<-c
}

func parseInternal(data io.Reader) {
	// b := bytes.NewBuffer(uint8ArrayToBytes(data))
	parser := dem.NewParser(data)

	header, err := parser.ParseHeader()
	checkError(err)
	fmt.Println("map: " + header.MapName)

	parser.RegisterEventHandler(func(e events.PlayerConnect) {
		fmt.Println("Player connect: " + e.Player.Name)
	})
	parser.RegisterEventHandler(func(e events.PlayerDisconnected) {
		fmt.Println("Player disconnect: " + e.Player.Name)
	})
	parser.RegisterEventHandler(func(e events.MatchStart) {
		fmt.Println("Match start ")
	})
	parser.RegisterEventHandler(func(e events.RoundStart) {
		fmt.Println("Round start " + e.Objective)
	})
	parser.RegisterEventHandler(func(e events.RoundEnd) {
		fmt.Println("Round end ", e.Message, " ; ", e.Reason)
	})
	parser.RegisterEventHandler(func(e events.RoundEndOfficial) {
		fmt.Println("Round end offc ")
	})

	err = parser.ParseToEnd()
	checkError(err)

	fmt.Println("end")
}

func checkError(err error) {
	if err != nil {
		log.Panic(err)
	}
}

```

Demo file: https://static.gamergalaxy.net/replays/csgo/003636976135146832149_1877073722.dem

Error: 
```
Round start BOMB TARGET
Round end  #SFUI_Notice_CTs_Win  ;  8
Round end offc 
Round start BOMB TARGET
Round end  #SFUI_Notice_Bomb_Defused  ;  7
Round end offc 
Round start BOMB TARGET
2023/09/11 21:26:33 runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 18 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x1006e94e0, 0x140005146b0})
        /Users/dab/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0-beta.0/pkg/demoinfocs/parser.go:388 +0x2c
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x48
panic({0x1006e94e0?, 0x140005146b0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/markus-wa/godispatch.callConsumerCode.func1()
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x60
panic({0x1006ba7e0?, 0x100b7bdc0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).HasDefuseKit(0x0)
        /Users/dab/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0-beta.0/pkg/demoinfocs/common/player.go:316 +0x1c
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).bindBomb.func2.2({{0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x100640550, 0x0}, ...})
        /Users/dab/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0-beta.0/pkg/demoinfocs/datatables.go:214 +0x1e0
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0x14000a6c380, 0x140002ad140?)
        /Users/dab/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0-beta.0/pkg/demoinfocs/sendtables2/entity.go:419 +0x1b4
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0x140000da0f0, 0x14000fa4270)
        /Users/dab/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0-beta.0/pkg/demoinfocs/sendtables2/entity.go:515 +0x458
reflect.Value.call({0x100698e40?, 0x140000bc438?, 0x140011b9dd8?}, {0x1005e9195, 0x4}, {0x140011b9ee0, 0x1, 0x0?})
        /usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x100698e40?, 0x140000bc438?, 0x100374c70?}, {0x140011b9ee0?, 0xb3000140011b9e58?, 0x2?})
        /usr/local/go/src/reflect/value.go:380 +0x94
github.com/markus-wa/godispatch.callConsumerCode({0x100698e40?, 0x140000bc438?, 0x140011b9e98?}, {0x140011b9ee0?, 0x1400034c460?, 0x0?})
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x44
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0x140000ae2a0, {0x10077c680, 0x14000fa4270})
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1fc
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0x140000ae2b8?, {0x10077c680?, 0x14000fa4270?})
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x50
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0x140000ae2a0, 0x0?)
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xcc
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
        /Users/dab/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x1ac
```

**Comment by akiver** [comment]
@sarim-hk I tried your code + demo on the V3 and V4 versions and it doesn't crash, are you sure it's the correct demo/code?  
Here is the output I got https://pastebin.com/whdyrgqH

@dabbers it's fixed in the last beta. Please upgrade to the last version (beta.1)

**Comment by markus-wa** [comment]
@sarim-hk the issue seems to be in `D:/Documents/Programming/Python/Counter-Strike/playtest_analyser/demoparser.go` line 81 - I assume this is your code?

```
        C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
main.main.func1({0xc00383cb40, 0xc0014049c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        D:/Documents/Programming/Python/Counter-Strike/playtest_analyser/demoparser.go:81 +0x70
```

**Comment by sarim-hk** [comment]
> @sarim-hk I tried your code + demo on the V3 and V4 versions and it doesn't crash, are you sure it's the correct demo/code? Here is the output I got https://pastebin.com/whdyrgqH

Ah, it wasn't the correct demo (but definitely the correct code!), I've uploaded the correct one here. https://drive.google.com/file/d/1qBvWiLD-ToybuUoNN7pP-YjIGWC6PZIn/view?usp=sharing

**Comment by sarim-hk** [comment]
> @sarim-hk the issue seems to be in `D:/Documents/Programming/Python/Counter-Strike/playtest_analyser/demoparser.go` line 81 - I assume this is your code?
> 
> ```
>         C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
> main.main.func1({0xc00383cb40, 0xc0014049c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
>         D:/Documents/Programming/Python/Counter-Strike/playtest_analyser/demoparser.go:81 +0x70
> ```

Is my code indeed, but I can't imagine what would be causing an error here? 

![image](https://github.com/markus-wa/demoinfocs-golang/assets/58489447/c3d05472-500d-4e47-b882-afcf5f321fd3)
![image](https://github.com/markus-wa/demoinfocs-golang/assets/58489447/acd656ef-4f4a-45e9-b9b2-336d5a96d670)

**Comment by markus-wa** [comment]
@sarim-hk `e.Killer` is nil, so you're getting a nil deref.

Maybe this death was a suicide?

**Comment by sarim-hk** [comment]
> @sarim-hk `e.Killer` is nil, so you're getting a nil deref.
> 
> Maybe this death was a suicide?

Ohh, good idea! It probably is exactly that, I'll have a look later and close the issue if it is. Thanks for the help :)
