### ISSUE TITLE
interface conversion: interface {} is *sendtables2.fieldState, not uint64

### ISSUE THREAD

**Issue by sarim-hk** [markus-wa/demoinfocs-golang#487]
**Describe the bug**
In the process of writing some code for my Google Cloud Function, I came across this error. This occurs when running my test code.

**Stacktrace**
```
2023/12/25 23:42:32 failed to parse demo:  interface conversion: interface {} is *sendtables2.fieldState, not uint64
stacktrace:
goroutine 9 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0xdf7ac0, 0xc0012c45d0})
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x30
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x42
panic({0xdf7ac0, 0xc0012c45d0})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x5f
panic({0xda7020, 0xc0012c3260})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables.PropertyValue.S2UInt64(...)
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables/propdecoder.go:152
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).bindPlayerWeaponsS2.func3({{0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0xfff0f0, 0x0}, ...})
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/datatables.go:732 +0x93
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc00009c140, 0xc000c18ea0)
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:568 +0x8f6
reflect.Value.call({0xd5a5c0?, 0xc000008780?, 0xc000108c90?}, {0xf11055, 0x4}, {0xc0004bdef8, 0x1, 0x2?})
        C:/Program Files/Go/src/reflect/value.go:586 +0xb07
reflect.Value.Call({0xd5a5c0?, 0xc000008780?, 0x0?}, {0xc0004bdef8?, 0xe100000000000000?, 0x3?})
        C:/Program Files/Go/src/reflect/value.go:370 +0xbc
github.com/markus-wa/godispatch.callConsumerCode({0xd5a5c0?, 0xc000008780?, 0xee1ec0?}, {0xc0004bdef8?, 0x66df59?, 0xc000056000?})
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00010c120, {0xee1ec0?, 0xc000c18ea0})
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x236
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc00010c138?, {0xee1ec0?, 0xc000c18ea0?})
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x5a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00010c120, 0x0?)
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
        C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x187

--- FAIL: TestDemoParser (0.02s)
    p_test.go:19: interface conversion: interface {} is *sendtables2.fieldState, not uint64
        stacktrace:
        goroutine 9 [running]:
        runtime/debug.Stack()
                C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
        github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0xdf7ac0, 0xc0012c45d0})
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x30
        github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x42
        panic({0xdf7ac0, 0xc0012c45d0})
                C:/Program Files/Go/src/runtime/panic.go:884 +0x213
        github.com/markus-wa/godispatch.callConsumerCode.func1()
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x5f
        panic({0xda7020, 0xc0012c3260})
                C:/Program Files/Go/src/runtime/panic.go:884 +0x213
        github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables.PropertyValue.S2UInt64(...)
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables/propdecoder.go:152
        github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).bindPlayerWeaponsS2.func3({{0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0xfff0f0, 0x0}, ...})      
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/datatables.go:732 +0x93
        github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc00009c140, 0xc000c18ea0)
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:568 +0x8f6
        reflect.Value.call({0xd5a5c0?, 0xc000008780?, 0xc000108c90?}, {0xf11055, 0x4}, {0xc0004bdef8, 0x1, 0x2?})
                C:/Program Files/Go/src/reflect/value.go:586 +0xb07
        reflect.Value.Call({0xd5a5c0?, 0xc000008780?, 0x0?}, {0xc0004bdef8?, 0xe100000000000000?, 0x3?})
                C:/Program Files/Go/src/reflect/value.go:370 +0xbc
        github.com/markus-wa/godispatch.callConsumerCode({0xd5a5c0?, 0xc000008780?, 0xee1ec0?}, {0xc0004bdef8?, 0x66df59?, 0xc000056000?})
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
        github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00010c120, {0xee1ec0?, 0xc000c18ea0})
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x236
        github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc00010c138?, {0xee1ec0?, 0xc000c18ea0?})
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x5a
        github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00010c120, 0x0?)
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
        created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
                C:/Users/Sarim/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x187

FAIL
```

**To Reproduce**
https://drive.google.com/file/d/1bDMVSrIAk8o-EWLqsIsjonAtIv9sCRwh/view?usp=sharing
Link to my code and the demo, occurs when running `go test`

**Versions**
go version go1.20.12 windows/amd64
github.com/markus-wa/demoinfocs-golang/v4 v4.0.0

**Comment by sarim-hk** [comment]
nevermind i just had to update to go 1.21 :) closed
