### ISSUE TITLE
Last cs2 update broke the module

### ISSUE THREAD

**Issue by maxpain** [markus-wa/demoinfocs-golang#527]
```
panic message: runtime error: invalid memory address or nil pointer dereference
stack trace: runtime error: invalid memory address or nil pointer dereference
goroutine 159 [running]:
runtime/debug.Stack()
	/layers/google.go.runtime/go/src/runtime/debug/stack.go:24 +0x5e
github.com/GoogleCloudPlatform/functions-framework-go/funcframework.recoverPanic({0x0, 0x0}, {0xfad987, 0x17}, 0x1)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/!google!cloud!platform/functions-framework-go@v1.8.1/funcframework/framework.go:53 +0xcc
panic({0xdbcda0?, 0x192d4e0?})
	/layers/google.go.runtime/go/src/runtime/panic.go:770 +0x132
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0xdbcda0, 0x192d4e0})
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.1.2/pkg/demoinfocs/parsing.go:171 +0x128
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.1.2/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0xdbcda0?, 0x192d4e0?})
	/layers/google.go.runtime/go/src/runtime/panic.go:770 +0x132
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc00037ae00)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.1.2/pkg/demoinfocs/parsing.go:359 +0x234
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc00037ae00)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.1.2/pkg/demoinfocs/parsing.go:147 +0x146
fastcup.net/replayVoiceExtractor.extractReplayVoices({0x10e3118, 0xc0006bc020}, {{0x10efe10, 0xc0007981c0}, {0xc0000b2800, 0x417, 0x800}, 0x0, 0x0})
	/workspace/serverless_function_source_code/main.go:111 +0x4c2
github.com/GoogleCloudPlatform/functions-framework-go/funcframework.wrapCloudEventFunction.func1({0x10e3118?, 0xc0006bc020?}, {{0x10efe10, 0xc0007981c0}, {0xc0000b2800, 0x417, 0x800}, 0x0, 0x0})
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/!google!cloud!platform/functions-framework-go@v1.8.1/funcframework/framework.go:294 +0xc3
reflect.Value.call({0xd869e0?, 0xc000422ab0?, 0x419fff?}, {0xf9c129, 0x4}, {0xc000be02a0, 0x2, 0xc0005c1a28?})
	/layers/google.go.runtime/go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0xd869e0?, 0xc000422ab0?, 0x20?}, {0xc000be02a0?, 0xc0006bc020?, 0x0?})
	/layers/google.go.runtime/go/src/reflect/value.go:380 +0xb9
github.com/cloudevents/sdk-go/v2/client.(*receiverFn).invoke(0xc000343050, {0x10e3118, 0xc0006bc020}, 0xc0006700c0)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.15.2/client/receiver.go:90 +0x27f
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func2(0xc0005c1e20, {0x10e3150?, 0xc000999630?}, 0xc0001593b0, 0xc0006700c0)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.15.2/client/invoker.go:93 +0x175
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke(0xc0001593b0, {0x10e3118, 0xc0006bc020}, {0x10e3150, 0xc000999630}, 0xc000be0180)
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.15.2/client/invoker.go:96 +0x37e
github.com/cloudevents/sdk-go/v2/client.(*EventReceiver).ServeHTTP.func1()
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.15.2/client/http_receiver.go:40 +0x1f7
created by github.com/cloudevents/sdk-go/v2/client.(*EventReceiver).ServeHTTP in goroutine 158
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.15.2/client/http_receiver.go:35 +0x74
```

**Comment by Froctnow** [comment]
Duplicate https://github.com/markus-wa/demoinfocs-golang/issues/525

**Comment by akiver** [comment]
Could you try with https://github.com/markus-wa/demoinfocs-golang/pull/529?

**Comment by maxpain** [comment]
> Could you try with #529?

yes, it's working, thanks!
