### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mavrick** [markus-wa/demoinfocs-golang#567]
**Describe the bug**
```bash
runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 19 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e  
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x7f4380?, 0xc0006be4b0})
        github.com/markus-wa/demoinfocs-golang/v4@v4.3.0/pkg/demoinfocs/parser.go:404 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x7f4380?, 0xc0006be4b0?})        
        runtime/panic.go:914 +0x21f      
github.com/markus-wa/godispatch.callConsumerCode.func1()
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x7f4380?, 0xc0006be4a0?})        
        runtime/panic.go:914 +0x21f      
github.com/markus-wa/godispatch.callConsumerCode.func1()
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x7c17e0?, 0xd7c7d0?})
        runtime/panic.go:914 +0x21f      
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).Health(0x0)
        github.com/markus-wa/demoinfocs-golang/v4@v4.3.0/pkg/demoinfocs/common/player.go:374 +0x25
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).IsAlive(0x0)
        github.com/markus-wa/demoinfocs-golang/v4@v4.3.0/pkg/demoinfocs/common/player.go:83 +0x2a
github.com/akiver/cs-demo-analyzer/pkg/api.newChatMessageFromGameEvent(0xc000110a00, {0x0?, {0xc00000b7b6?, 0xc000906e90?}, 0x15?})
        github.com/akiver/cs-demo-analyzer/pkg/api/chat_message.go:25 +0x65       
github.com/akiver/cs-demo-analyzer/pkg/api.(*Analyzer).registerCommonHandlers.func36({0x0?, {0xc00000b7b6?, 0x0?}, 0x73?}) 
        github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:1102 +0x3c
reflect.Value.call({0x788520?, 0xc000118a50?, 0xc00034e120?}, {0x8b50e0, 0x4}, {0xc0009075f8, 0x1, 0x4?})
        reflect/value.go:596 +0xce7      
reflect.Value.Call({0x788520?, 0xc000118a50?, 0x0?}, {0xc0009075f8?, 0xac00000000000000?, 0x5?})
        reflect/value.go:380 +0xb9       
github.com/markus-wa/godispatch.callConsumerCode({0x788520?, 0xc000118a50?, 0x7fde20?}, {0xc0009075f8?, 0x7fde20?, 0x40?}) 
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000248600, {0x7fde20, 0xc000894480})
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleMessageSayText2(0xc0002d6c40, 0xc0005065a0)       
        github.com/markus-wa/demoinfocs-golang/v4@v4.3.0/pkg/demoinfocs/net_messages.go:136 +0x4b1
reflect.Value.call({0x789ea0?, 0xc00010aee0?, 0xc0002e7b60?}, {0x8b50e0, 0x4}, {0xc000907ef8, 0x1, 0x2?})
        reflect/value.go:596 +0xce7      
reflect.Value.Call({0x789ea0?, 0xc00010aee0?, 0x0?}, {0xc000907ef8?, 0x7e00000000000000?, 0x3?})
        reflect/value.go:380 +0xb9       
github.com/markus-wa/godispatch.callConsumerCode({0x789ea0?, 0xc00010aee0?, 0x869420?}, {0xc000907ef8?, 0xc00009a800?, 0x40dbae?})
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0002485a0, {0x869420, 0xc0005065a0})
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0002485b8?, {0x869420?, 0xc0005065a0?})
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0002485a0, 0x0?)   
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1 
        github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a
```

**To Reproduce**
Demo file: https://drive.google.com/file/d/1FmFS07Db-i9-estriuTUrcjrdfDs9OaR/view?usp=sharing

**Library version**
v4.3.0

**Additional context**
OS: Win11
Node.js v20.15.1
@akiver/cs-demo-analyzer - v1.4.11

**Comment by mavrick** [comment]
@akiver
